# Generated by Django 5.2.15 on 2026-06-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('operator', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('affected_routes', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('severe', 'Severe')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['is_active', '-start_time'], name='rail_disrup_is_acti_e72267_idx'), models.Index(fields=['severity'], name='rail_disrup_severit_31027d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(db_index=True, max_length=20, unique=True)),
                ('uid', models.CharField(blank=True, max_length=10)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(blank=True, max_length=5)),
                ('scheduled_dep', models.DateTimeField(blank=True, null=True)),
                ('estimated_dep', models.DateTimeField(blank=True, null=True)),
                ('actual_dep', models.DateTimeField(blank=True, null=True)),
                ('scheduled_arr', models.DateTimeField(blank=True, null=True)),
                ('estimated_arr', models.DateTimeField(blank=True, null=True)),
                ('actual_arr', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('arrived', 'Arrived'), ('departed', 'Departed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_services', to='rail.station')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_services', to='rail.station')),
            ],
            options={
                'ordering': ['-scheduled_dep'],
                'indexes': [models.Index(fields=['status'], name='rail_servic_status_d03692_idx'), models.Index(fields=['scheduled_dep'], name='rail_servic_schedul_2894b5_idx')],
            },
        ),
    ]
